### ISSUE TITLE
Can't run test on chapter 1

### ISSUE THREAD

**Issue by jhagege** [last-ent/distributed-go#1]
Hi, cool book !

Problem with tests on chapter 1:

```
Joachims-MacBook-Pro:chapter1 joachimhagege$ go test
# github.com/last-ent/distributed-go/chapter1
./variadic_test.go:51: Errorf format %s has arg numbers of wrong type []int
FAIL    github.com/last-ent/distributed-go/chapter1 [build failed]

```

**Comment by jhagege** [comment]
I succeed to run it from GoLand IDE.
But not from command line

**Comment by jhagege** [comment]
I tried with 1.9.1, it works. 
Not sure why there is a regression with 1.10.3

**Comment by last-ent** [comment]
Hi @jhagege, thanks for checking out the book and raising the issue :)

I will create a PR to fix this but in order for you to move forward, please replace line# 51 with

```golang
t.Errorf("Received unexpected values: %s, %v", name, numbers)
```

Hope it helps!

**Comment by last-ent** [comment]
@jhagege You can take the latest pull of the repository and everything should be fine.
